#!/bin/bash


ACTION="$1"
shift

PATCH_DIR="/usr/share/zero-lliurex-luanti"
INSTALL_DIR="/usr/share/games/minetest/builtin/mainmenu/"
PACKAGE_LIST=$@

case $ACTION in
	preInstall)
		apt install minetest -y
	;;
	postInstall)
		patch -t -N ${INSTALL_DIR}/serverlistmgr.lua ${PATCH_DIR}/01_disable_serverlist.patch
		if [[ " ${PACKAGE_LIST[*]} " != *" luanti-server "* ]]; then
			patch --silent -t -N ${INSTALL_DIR}/tab_local.lua ${PATCH_DIR}/02_disable_server.patch
		else
			echo "Enabling server mode"
		 	patch --silent --dry-run -f  ${INSTALL_DIR}/tab_local.lua ${PATCH_DIR}/02_disable_server.patch || \
				patch --silent -t  ${INSTALL_DIR}/tab_local.lua ${PATCH_DIR}/02_disable_server.patch
		fi
		echo "**** Luanti/Minetest configured ****"
	;;
	remove)
		for ix in $PACKAGE_LIST	
		do
			apt-get remove -y $ix
			TEST=$( dpkg-query -s  $ix 2> /dev/null| grep Status | cut -d " " -f 4 )
			if [ "$TEST" == 'installed' ];then
				exit 1

			fi
		done
	;;	
esac	

