#!/bin/bash


ACTION="$1"
shift

MINETEST_PKG="minetest"
PATCH_DIR="/usr/share/zero-lliurex-luanti"
INSTALL_DIR="/usr/share/luanti/builtin/mainmenu/"
PACKAGE_LIST=$@

case $ACTION in
	getStatus)
		TEST=0
		if dpkg -s $MINETEST_PKG >/dev/null 2>&1 ;then
			if [[ " ${PACKAGE_LIST[*]} " == *" Luanti "* ]]; then
				patch --silent --dry-run -f  ${INSTALL_DIR}/tab_local.lua ${PATCH_DIR}/02_disable_server.patch 1>/dev/null 2>&1
				if [ $? -ne 0 ] ;then
					TEST=0
				fi
			fi
			if [[ " ${PACKAGE_LIST[*]} " == *" Luanti-server "* ]]; then
				patch --silent --dry-run -f  ${INSTALL_DIR}/tab_local.lua ${PATCH_DIR}/02_disable_server.patch 1>/dev/null 2>&1
				if [ $? -ne 0 ] ;then
					TEST=1
				fi
			fi
		else
			TEST=1
		fi
		echo $TEST
	;;

	installPackage)
		dpkg -s $MINETEST_PKG >/dev/null 2>&1 || apt install -y $MINETEST_PKG
		patch -t -N ${INSTALL_DIR}/serverlistmgr.lua ${PATCH_DIR}/01_disable_serverlist.patch 1>/dev/null 2>&1
		if [[ " ${PACKAGE_LIST[*]} " != *" Luanti-server "* ]]; then
			patch --silent -t -N ${INSTALL_DIR}/tab_local.lua ${PATCH_DIR}/02_disable_server.patch 1>/dev/null 2>&1
		else
			echo "Enabling server mode"
		 	patch --silent --dry-run -f  ${INSTALL_DIR}/tab_local.lua ${PATCH_DIR}/02_disable_server.patch 1>/dev/null 2>&1 || \
				patch --silent -t  ${INSTALL_DIR}/tab_local.lua ${PATCH_DIR}/02_disable_server.patch 1>/dev/null 2>&1
		fi
		echo "**** Luanti/Minetest configured ****"
	;;
	remove)
		apt remove -y $MINETEST_PKG || true
		rm -fr /usr/share/luanti/ 2>/dev/null || true
	;;	
esac	

exit 0
